[build]
  command = "export NODE_OPTIONS=--openssl-legacy-provider && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build.environment]
  NODE_VERSION = "18.17.0" 