import React from 'eslint-plugin-import/config/react';
import classNames from 'classnames';
// import Text from './typography';
import {
	ArrowLeftIcon,
	ArrowRightIcon,
	ArrowUpRightIcon,
	ArrowUpLeftIcon,
	ChatBubbleBottomCenterIcon,
	ExclamationCircleIcon,
	CalendarIcon,
} from '@heroicons/react/24/solid';

const calendar = [
	{
		id: 0,
		year: 2023,
		months: [
			{
				id: 0,
				cashflow: 1333,
				deposit: 100,
				withdraw: 21,
				month: 'January',
				note: true,
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 1,
				cashflow: 1333,
				deposit: 100,
				withdraw: 21,
				month: 'February',
				note: true,
				active: true,
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						active: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
				],
			},
			{
				id: 2,
				cashflow: 3012,
				month: 'March',
				action: true,
				trend: 'UpLeft',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 3,
				cashflow: 100,
				month: 'April',
				trend: 'UpRight',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
				],
			},
			{
				id: 4,
				cashflow: 89,
				month: 'May',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 5,
				cashflow: 89,
				month: 'June',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
				],
			},
			{
				id: 6,
				cashflow: 89,
				month: 'Jule',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 7,
				cashflow: 89,
				month: 'August',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 8,
				cashflow: 89,
				month: 'September',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
				],
			},
			{
				id: 9,
				cashflow: 89,
				month: 'October',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
			{
				id: 10,
				cashflow: 89,
				month: 'November',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
				],
			},
			{
				id: 11,
				cashflow: 89,
				month: 'December',
				days: [
					{
						id: 0,
						date: 1,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Sunday',
					},
					{
						id: 1,
						date: 2,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 2,
						date: 3,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 3,
						date: 4,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 4,
						date: 5,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 5,
						date: 6,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
						note: true,
					},
					{
						id: 6,
						date: 7,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 7,
						date: 8,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 8,
						date: 9,
						cashflow: 13,
						deposit: 100,
						withdraw: 21,
						note: true,
						trend: 'UpLeft',
						day: 'Monday',
					},
					{
						id: 9,
						date: 10,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 10,
						date: 11,
						cashflow: 3,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 11,
						date: 12,
						cashflow: 99,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 12,
						date: 13,
						cashflow: 46,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 13,
						date: 14,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
						note: true,
					},
					{
						id: 14,
						date: 15,
						cashflow: 0,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
						note: true,
					},
					{
						id: 15,
						date: 16,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 16,
						date: 17,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 17,
						date: 18,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 18,
						date: 19,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 19,
						date: 20,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 20,
						date: 21,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 21,
						date: 22,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 22,
						date: 23,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 23,
						date: 24,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
					{
						id: 24,
						date: 25,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Wednesday',
					},
					{
						id: 25,
						date: 26,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Thursday',
					},
					{
						id: 26,
						date: 27,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Friday',
					},
					{
						id: 27,
						date: 28,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Saturday',
					},
					{
						id: 28,
						date: 29,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Sunday',
					},
					{
						id: 29,
						date: 30,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Monday',
					},
					{
						id: 30,
						date: 31,
						cashflow: 123,
						deposit: 100,
						withdraw: 21,
						day: 'Tuesday',
					},
				],
			},
		],
	},
];

const CalendarHeader = () => {
	return (
		<div className="calendar-header flex items-center align-center justify-center gap-2">
			<select
				id="small"
				className="inline p-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50"
			>
				<option selected>2023</option>
				<option value="2024">2024</option>
			</select>
			<button
				type="button"
				className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
			>
				<CalendarIcon className="h-3 w-3 text-gray-900" />
			</button>
		</div>
	);
};

const Cell = ({ year }) => {
	return (
		<>
			{year.months.map((month) => {
				return (
					<div
						key={month?.id}
						className={classNames(
							`flex group hover:bg-purple-500 hover:shadow-lg hover-dark-shadow rounded-lg mx-1 cursor-pointer justify-center w-full`,
							month?.active &&
								`flex group bg-purple-600 shadow-lg dark-shadow rounded-lg mx-1 cursor-pointer justify-center relative`
						)}
					>
						<div className="flex items-center px-4 py-4 relative">
							<div className="text-center">
								<p
									className={classNames(
										`text-gray-900 group-hover:text-gray-100 text-sm flex gap-2 text-center justify-center items-center align-center`,
										month?.active && `text-gray-100 text-sm`
									)}
								>
									<p>+ {month?.cashflow}</p>
									{month?.trend === 'UpRight' && (
										<button
											type="button"
											className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
										>
											<ArrowUpRightIcon className="h-3 w-3 text-gray-900" />
										</button>
									)}
									{month?.trend === 'UpLeft' && (
										<button
											type="button"
											className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
										>
											<ArrowUpLeftIcon className="h-3 w-3 text-gray-900" />
										</button>
									)}
								</p>
								<p
									className={classNames(
										`text-gray-900 group-hover:text-purple-900 mt-3 group-hover:font-bold`,
										month?.active &&
											`text-gray-100  mt-3 font-bold`
									)}
								>
									{month?.month}
								</p>
								{month?.action && (
									<button
										type="button"
										className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
									>
										<ExclamationCircleIcon className="h-4 w-4 text-gray-900 mx-auto" />
									</button>
								)}
								{month?.note && (
									<button
										type="button"
										className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
									>
										<ChatBubbleBottomCenterIcon className="h-4 w-4 text-gray-900 mx-auto" />
									</button>
								)}
							</div>
							{month?.active && (
								<span className="flex h-3 w-3 absolute -top-1 -right-1">
									<span className="animate-ping absolute group-hover:opacity-75 opacity-0 inline-flex h-full w-full rounded-full bg-purple-400" />
									<span className="relative inline-flex rounded-full h-3 w-3 bg-purple-100" />
								</span>
							)}
						</div>
					</div>
				);
			})}
		</>
	);
};

const CalendarMonths = ({ year }) => {
	return (
		<div className="calendar-slim calendar-year flex">
			<button
				type="button"
				className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
			>
				<ArrowLeftIcon className="h-4 w-4 text-gray-900" />
			</button>

			<div className="flex w-full bg-white shadow-md justify-start md:justify-center rounded-lg overflow-x-scroll mx-auto py-4 px-2 md:mx-12">
				<Cell year={year} />
			</div>

			<button
				type="button"
				className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
			>
				<ArrowRightIcon className="h-4 w-4 text-gray-900" />
			</button>
		</div>
	);
};

const CalendarYearly = ({ year }) => {
	return (
		<div className="calendar-full calendar-yearly flex">
			<button
				type="button"
				className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
			>
				<ArrowLeftIcon className="h-4 w-4 text-gray-900" />
			</button>

			<div className="grid grid-cols-3 flex-grow gap-2 mx-auto py-4 px-2 md:mx-12">
				{year.months.map((month) => {
					return (
						<div
							key={month.id}
							className={classNames(
								`bg-white rounded-lg overflow-hidden p-4`,
								month?.active &&
									`bg-white rounded-lg overflow-hidden`
							)}
						>
							<div className="flex items-center justify-between py-2 px-0">
								<p className="text-gray-400 text-xs font-medium uppercase">
									{month?.month}
								</p>
							</div>
							<div className="grid grid-cols-7 flex-grow gap-1 pt-1">
								{month?.days?.map((day) => {
									return (
										<div
											key={day?.id}
											className={classNames(
												`px-2 py-2 w-full rounded-lg hover:shadow cursor-pointer`,
												day?.active &&
													`px-2 py-2 w-full rounded-lg shadow`
											)}
										>
											<div className="px-0 py-0 w-full">
												<p
													className={classNames(
														`text-xs inline-flex p-2 items-center justify-center cursor-pointer text-center leading-none rounded-full text-gray-400 flex flex-row gap-2`,
														day?.active &&
															`inline-flex items-center justify-center cursor-pointer text-center leading-none rounded-full text-gray-900 font-medium`
													)}
												>
													{day?.date}
													{day?.note && (
														<button
															type="button"
															className="font-medium rounded-full text-sm p-0 text-center inline-flex items-center ml-auto"
														>
															<ChatBubbleBottomCenterIcon className="h-3 w-3 text-gray-900 mx-auto" />
														</button>
													)}
												</p>
												<p className="flex gap-1 flex-row text-center justify-center items-center align-center">
													<p
														className={classNames(
															`text-gray-400 text-sm flex-wrap truncate`,
															day?.active &&
																`text-gray-800 text-sm flex-wrap truncate`
														)}
													>
														+ {day?.cashflow}
													</p>
													{day?.trend ===
														'UpRight' && (
														<button
															type="button"
															className="font-medium rounded-full text-sm p-0 text-center inline-flex items-center"
														>
															<ArrowUpRightIcon className="h-3 w-3 text-gray-900" />
														</button>
													)}
													{day?.trend ===
														'UpLeft' && (
														<button
															type="button"
															className="font-medium rounded-full text-sm p-0 text-center inline-flex items-center"
														>
															<ArrowUpLeftIcon className="h-3 w-3 text-gray-900" />
														</button>
													)}
												</p>
												{day?.action && (
													<button
														type="button"
														className="font-medium rounded-full text-sm p-0 text-center inline-flex items-center"
													>
														<ExclamationCircleIcon className="h-3 w-3 text-gray-900 mx-auto" />
													</button>
												)}
											</div>
										</div>
									);
								})}
							</div>
						</div>
					);
				})}
			</div>

			<button
				type="button"
				className="font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center"
			>
				<ArrowRightIcon className="h-4 w-4 text-gray-900" />
			</button>
		</div>
	);
};

const Calendar = () => {
	return (
		<div className="w-full">
			{calendar.map((year) => {
				return (
					<div
						key={year?.id}
						className="calendar flex flex-col w-full bg-white py-4"
					>
						<CalendarHeader />

						<CalendarMonths year={year} />

						<CalendarYearly year={year} />
					</div>
				);
			})}
		</div>
	);
};

export default Calendar;
